version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5137:5137"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    networks:
      - shared-network

networks:
  shared-network:
    external: true
