version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: authentication-service
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
      - 8443:8443
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    networks:
      - shared-network

networks:
  shared-network:
    external: true
